name: last02
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  animations: 2.0.8
  cached_network_image: 3.3.0
  dio: 5.3.3
  font_awesome_flutter: 10.6.0
  flutter_localizations:
    sdk: flutter
  fluttertoast: 8.2.10
  flutter_svg: 2.0.8
  get: 4.6.6
  intl: ^0.20.2
  logger: 2.0.2+1
  pretty_dio_logger: 1.3.1
  shared_preferences: 2.2.2
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.3.0
  freezed_annotation: ^2.4.1
  flutter_native_splash: ^2.3.10
  dropdown_button2: ^2.3.9
  json_annotation: ^4.8.1
  flutter_card_swiper: ^7.0.2
  flutter_tts: ^4.2.2
  mobile_scanner: ^7.0.0
  just_audio: ^0.10.3
  image_picker: ^1.1.2
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^18.0.1
  cloud_firestore: ^5.6.9
  permission_handler: ^12.0.0+1
  flutter_html: ^3.0.0
  html: ^0.15.6
  shimmer: ^3.0.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: 5.13.0
  dart_code_metrics: any
  change_app_package_name: 1.1.0
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/
    - .env
